### ISSUE TITLE
Progress information?

### ISSUE THREAD

**Issue by glenjamin** [mmazzarolo/ordinary-puzzles-app#13]
As I complete levels, I see my count of stars go up, but I think it would help my sense of progress if there was a list of previously completed levels and I could view the solutions I did for each one

**Comment by mmazzarolo** [comment]
👋 @glenjamin ! 
That’s something I’ve been thinking for a while. 
My initial idea for this game was to actually show the entire progress in the main screen, but from the initial feedback nobody was “that” interested, so I went for the current approach. 
One thing that was suggested on Hacker News is to create a new screen that shows the current progress, available by tapping on the score/star at the top right of the main menu. What do you think about it?
Any other ideas?

**Comment by mmazzarolo** [comment]
@glenjamin just added a "Statistics" screen, see #16 
It's not the best solution to the issue, but we can use it as a starting point :)
