### ISSUE TITLE
Tutorial ambigious

### ISSUE THREAD

**Issue by daveloyall** [mmazzarolo/ordinary-puzzles-app#2]
Hello.

Pretend that you don't know how to play the game at all.  (I did not a minute ago.)

In the tutorial, on the second screen, drag the three all the way to the right (a line four blocks long).  Now, drag the 4 all the way to the left (a line four blocks long).

Ok, I followed the instructions in the tutorial.  Now it just sits there.. I tap some things..  Nothing happens.

The tutorial does move to the next screen if I make the 3-line 3 blocks long and the 4-line 4 blocks long.  So, I think the length of lines matters!  (Right?)

The tutorial should have a step that shows the user how to make lines the correct length.

**Comment by mmazzarolo** [comment]
Thanks for the feedback @daveloyall ! 

I worked on a few different iterations of the tutorial, made a few internal testing and the current one was the one that seemed to be the more intuitive... But creating tutorial is way more complex than I expected, I received different feedbacks everytime someone played it.

In this specific case, it seemed that highlighting the lines that weren't valid would have been enough but I guess I was wrong. 

![IMAGE 2019-12-19 12:24:46](https://user-images.githubusercontent.com/9536354/71169986-8b701180-225a-11ea-83e4-8a25fd76d6c0.jpg)

I'm thinking about adding a step (before the one above ☝️ ) with a 4x2 grid, and a 3 in the corner, explaining that the line should have the same length of the number. 
What do you think?

**Comment by daveloyall** [comment]
Well, you can just tell the user with text, yes.

But, it may be more fun to just say "only some lines are valid!" and let them figure it out.  The small board you described would be useful for that, yes.

I didn't notice the highlighting until I started playing the game itself.
> The eye don't see what the mind don't know
--Somebody

When there is one line, maybe I just think it changes colors sometimes.  When there are two lines and one of them is invalid, maybe I just think different lines have different colors.

Parting thought: now that I know how to play, I won't be useful for tutorial feedback anymore.  I could try and pretend that I don't know the game mechanics, but, that's not as useful as feedback from a true neophyte!

**Comment by mmazzarolo** [comment]
@daveloyall the problem with the tutorials, is that there's not bullet-proof solution. 
For example, see this user on Hacker News who had a totally different experience and idea from yours (https://news.ycombinator.com/item?id=21834409). 

> Parting thought: now that I know how to play, I won't be useful for tutorial feedback anymore. I could try and pretend that I don't know the game mechanics, but, that's not as useful as feedback from a true neophyte!

😬 That's why I had to find new people for testing each tutorial improvements.
