### ISSUE TITLE
How do I know which player has won?

### ISSUE THREAD

**Issue by ducgiangtrankma** [mmazzarolo/ordinary-puzzles-app#37]
I can't find the code that handles this. Can you support me ?

**Comment by mmazzarolo** [comment]
Yup, it's [here](https://github.com/mmazzarolo/ordinary-puzzles-app/blob/b53f5b6f8351b5f701c2896f73c97a9aa23a4ee7/src/op-board/store.ts#L427-L443). May I ask you what do you need it for?

**Comment by ducgiangtrankma** [comment]
Tks you ! I need to understand when a player will finish part of their game
!

Vào Th 5, 14 thg 1, 2021 vào lúc 15:46 Matteo Mazzarolo <
notifications@github.com> đã viết:

**Comment by ducgiangtrankma** [comment]
Thank you for your support, that's great


Vào Th 5, 14 thg 1, 2021 vào lúc 15:48 Giang Trần Đức <
tranducgiangact@gmail.com> đã viết:
