### ISSUE TITLE
Inquiry about permissions for use in study

### ISSUE THREAD

**Issue by AshQTan** [mmazzarolo/ordinary-puzzles-app#38]
Hello,

My name is Ash Tan, and I was hoping to inquire about obtaining permission to use your code in the context of a scientific study regarding the effects of reward systems in games/mobile apps.  My colleagues and I are currently part of the Masters of Information and Data Science program at the Berkeley School of Information, and we are planning on running this study over the next few weeks as a project for our coursework.  We do not intend to profit from this study in any way, and the authors of this repository would be fully credited for the development of the puzzle app.  We would be happy to discuss the details of our study in a private conversation, and thank you for your consideration!

**Comment by mmazzarolo** [comment]
Hi Ash, thanks for getting in touch! 

You can find my email address on my profile; could you please also cc https://www.snellman.net/?

I'm closing the issue here because this discussion would work better via email and it's not an "issue" of the project.

Thank you!

cc @jsnell FYI ☝️
