### ISSUE TITLE
Tick sound stops audio (music, audiobook, etc)

### ISSUE THREAD

**Issue by boringparty** [mmazzarolo/ordinary-puzzles-app#47]
with iOS, if you're listening to music and want to play a game, the tick sound for a new game will stop the music. Prior versions would act more as a notification.

**Comment by mmazzarolo** [comment]
Hi @hello-party ! 

By:
> Prior versions would act more as a notification.

Do you mean older versions of Ordinary Puzzles? I haven't updated it in ages

**Comment by boringparty** [comment]
It must be related to IOS 14.3. Everything is working perfectly with iOS 14.5. Very strange. I'm on a jailbroken SE1.

14.2 was perfect, 14.3 had the glitch, I skipped 14.4, and now 14.5 is back to good again.

Since I can't reproduce it, this might as well be closed off. Thanks for this excellent game!
