### ISSUE TITLE
Changing ”quit” to ”menu”

### ISSUE THREAD

**Issue by luigibrosse** [mmazzarolo/ordinary-puzzles-app#7]
Really love your game so far.
Just a thought, but your ”quit” button actually does not quit, but instead bring you to the menu. Where you can actually press ”continue” to come back to your game. That seems a bit misleading to me. Again, not a major issue.

**Comment by mmazzarolo** [comment]
Hi @luigibrosse ! 
Thanks for reporting, I think this is a neat suggestion :) 
Want to submit a PR for it? Otherwise I can do it 👍
